version: '3.8'

networks:
    backend:

services:
    postgres:
        container_name: postgres_container
        image: postgres
        ports:
            - "5432:5432"
        environment:
            POSTGRES_DB: "filter"
            POSTGRES_USER: "postgres"
            POSTGRES_PASSWORD: "qwerty"
        volumes:
            - ./volumes/2. Init Database:/docker-entrypoint-initdb.d
            - ./volumes/postgres-data:/var/lib/postgresql/data
        restart: unless-stopped
        healthcheck:
            test: [ "CMD-SHELL", "pg_isready -U postgres" ]
            interval: 20s
            timeout: 5s
            retries: 5
            start_period: 10s