rabbit:
    queue: ${FILTER_QUEUE}
    exchange: ${FILTER_EXCHANGE}

similarity:
    smoothing-factor: 0.00001

times:
    time-update-filter: ${TIME_UPDATE_FILTER}
    time-update-similarity: ${TIME_UPDATE_SIMILARITY}

server:
    port: 8081

spring:
    jpa:
        defer-datasource-initialization: false
        properties:
            hibernate:
                format_sql: true
                generate_statistics: false
                jdbc:
                    batch_size: 50
                    fetch_size: 50
                order_updates: true
                order_insert: true
        open-in-view: false
        show-sql: false
        hibernate:
            ddl-auto: create
    datasource:
        url: ${DB_URL}
        username: ${DB_USERNAME}
        password: ${DB_PASSWORD}
        driver-class-name: org.postgresql.Driver

    rabbitmq:
        host: ${RABBIT_HOST}
        username: ${RABBIT_USERNAME}
        password: ${RABBIT_PASSWORD}
        port: ${RABBIT_PORT}

    application:
        name: collaborative-filter


logging:
    level:
        root: info