#rabbit:
#    queue: scrapper-queue
#    exchange: scrapper-exchange

similarity:
    update-factor: 0.1

server:
    port: 8080

spring:
    jpa:
        defer-datasource-initialization: false
        properties:
            hibernate:
                format_sql: true
                generate_statistics: false
                jdbc:
                    batch_size: 50
                    fetch_size: 50
                order_updates: true
                order_insert: true
        open-in-view: true
        show-sql: true
        hibernate:
            ddl-auto: create
    datasource:
        url: "jdbc:postgresql://localhost:5432/filter"
        username: postgres
        password: qwerty
        driver-class-name: org.postgresql.Driver

#    rabbitmq:
#        host: ${RABBIT_HOST}
#        username: user
#        password: qwerty
#        port: 5672

    application:
        name: collaborative-filter
